= The Cassandra Query Language (CQL)

This document describes the Cassandra Query Language
(CQL)footnote:[Technically, this document CQL version 3, which is not
backward compatible with CQL version 1 and 2 (which have been deprecated
and remove) and differs from it in numerous ways.]. Note that this
document describes the last version of the languages. However, the
link:#changes[changes] section provides the diff between the different
versions of CQL.

CQL offers a model close to SQL in the sense that data is put in
_tables_ containing _rows_ of _columns_. For that reason, when used in
this document, these terms (tables, rows and columns) have the same
definition than they have in SQL.
:toc:

== link:definitions/index.html[Definitions]
== link:types/index.html[Types] 
== link:ddl/index.html[DDL] 
== link:dml/index.html[DML] 
== link:indexes/index.html[Indexes] 
== link:mvs/index.html[MVs] 
== link:security/index.html[Security] 
== link:functions/index.html[Functions] 
== link:operators/index.html[Operators] 
== link:json/index.html[JSON]
== link:triggers/index.html[Triggers]
== link:appendices/index.html[Appendices]
== link:changes/index.html[Changes]
