= The Cassandra Query Language (CQL)

This document describes the Cassandra Query Language
(CQL)footnote:[Technically, this document CQL version 3, which is not
backward compatible with CQL version 1 and 2 (which have been deprecated
and remove) and differs from it in numerous ways.]. Note that this
document describes the last version of the languages. However, the
link:#changes[changes] section provides the diff between the different
versions of CQL.

CQL offers a model close to SQL in the sense that data is put in
_tables_ containing _rows_ of _columns_. For that reason, when used in
this document, these terms (tables, rows and columns) have the same
definition than they have in SQL.

* xref:cql/definitions.adoc[Definitions]
* xref:cql/types.adoc[Data types]
* xref:cql/ddl.adoc[DDL]
* xref:cql/dml.adoc[DML]
* xref:cql/indexes.adoc[Indexes]
* xref:cql/mvs.adoc[Materialized Views]
* xref:cql/functions.adoc[Functions]
* xref:cql/operators.adoc[Operators]
* xref:cql/json.adoc[JSON]
* xref:cql/security.adoc[Security]
* xref:cql/triggers.adoc[Triggers]
* xref:cql/appendices.adoc[Appendices]
* xref:cql/changes.adoc[Changes]
