= Installing Cassandra

These are the instructions for deploying the supported releases of
Apache Cassandra on Linux servers.

Cassandra runs on a wide array of Linux distributions including (but not
limited to):

* Ubuntu, most notably LTS releases 16.04 to 18.04
* CentOS & RedHat Enterprise Linux (RHEL) including 6.6 to 7.7
* Amazon Linux AMIs including 2016.09 through to Linux 2
* Debian versions 8 & 9
* SUSE Enterprise Linux 12

This is not an exhaustive list of operating system platforms, nor is it
prescriptive. However users will be well-advised to conduct exhaustive
tests of their own particularly for less-popular distributions of Linux.
Deploying on older versions is not recommended unless you have previous
experience with the older distribution in a production environment.

== Prerequisites

* Install the latest version of Java 8, either the
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle
Java Standard Edition 8] or http://openjdk.java.net/[OpenJDK 8]. To
verify that you have the correct version of java installed, type
`java -version`.
* *NOTE*: _Experimental_ support for Java 11 was added in Cassandra 4.0
(https://issues.apache.org/jira/browse/CASSANDRA-9608[CASSANDRA-9608]).
Running Cassandra on Java 11 is _experimental_. Do so at your own risk.
For more information, see
https://github.com/apache/cassandra/blob/trunk/NEWS.txt[NEWS.txt].
* For using cqlsh, the latest version of
https://www.python.org/downloads/[Python 2.7] or Python 3.6+. To verify
that you have the correct version of Python installed, type
`python --version`.

== Choosing an installation method

For most users, installing the binary tarball is the simplest choice.
The tarball unpacks all its contents into a single location with
binaries and configuration files located in their own subdirectories.
The most obvious attribute of the tarball installation is it does not
require `root` permissions and can be installed on any Linux
distribution.

Packaged installations require `root` permissions. Install the RPM build
on CentOS and RHEL-based distributions if you want to install Cassandra
using YUM. Install the Debian build on Ubuntu and other Debian-based
distributions if you want to install Cassandra using APT. Note that both
the YUM and APT methods required `root` permissions and will install the
binaries and configuration files as the `cassandra` OS user.

== Installing the binary tarball

[arabic]
. Verify the version of Java installed. For example:

[source,shell]
----
include::example$java_verify.sh[]
----
should return:

[source,plaintext]
----
include::example$java_verify.result[]
----

[arabic, start=2]
. Download the binary tarball from one of the mirrors on the
http://cassandra.apache.org/download/[Apache Cassandra Download] site.
For example, to download Cassandra 4.0:

[source,shell]
----
include::example$curl_install.sh[]
----

NOTE: The mirrors only host the latest versions of each major supported
release. To download an earlier version of Cassandra, visit the
http://archive.apache.org/dist/cassandra/[Apache Archives].

[arabic, start=3]
. OPTIONAL: Verify the integrity of the downloaded tarball using one of
the methods https://www.apache.org/dyn/closer.cgi#verify[here]. For
example, to verify the hash of the downloaded file using GPG:

[source,shell]
----
include::example$verify_gpg.sh[]
----

should return:

[source,plaintext]
----
include::example$verify_gpg.result[]
----

Compare the signature with the SHA256 file from the Downloads site:

[source,shell]
----
include::example$curl_verify_sha.sh[]
----

which returns: 

[source,plaintext]
----
28757dde589f70410f9a6a95c39ee7e6cde63440e2b06b91ae6b200614fa364d
----

[arabic, start=4]
. Unpack the tarball:

[source,shell]
----
include::example$tarball.sh[]
----

The files will be extracted to the `apache-cassandra-4.0.0/` directory.
This is the tarball installation location.

[arabic, start=5]
. Located in the tarball installation location are the directories for
the scripts, binaries, utilities, configuration, data and log files:

[source,plaintext]
----
include::example$tarball_install_dirs.txt[]
----
<1> location of the commands to run cassandra, cqlsh, nodetool, and SSTable tools
<2> location of cassandra.yaml and other configuration files
<3> location of the commit logs, hints, and SSTables
<4> location of system and debug logs
<5>location of cassandra-stress tool

For information on how to configure your installation, see
http://cassandra.apache.org/doc/latest/getting_started/configuring.html[Configuring
Cassandra].

[arabic, start=6]
. Start Cassandra:

[source,shell]
----
include::example$start_tarball.sh
----

NOTE: This will run Cassandra as the authenticated Linux user.

You can monitor the progress of the startup with:

[source,shell]
----
include::example$tail_syslog.sh
----

Cassandra is ready when you see an entry like this in the `system.log`:

[source,plaintext]
----
include::example$tail_syslog.result
----

[arabic, start=7]
. Check the status of Cassandra:

[source,shell]
----
include::example$nodetool_status.sh
----

The status column in the output should report UN which stands for
"Up/Normal".

Alternatively, connect to the database with:

[source,shell]
----
$ bin/cqlsh
----

== Installing the Debian packages

[arabic]
. Verify the version of Java installed. For example:

// LLP: NEED TO ADD TO PARTIALS TO REUSE
[source,shell]
----
$ java -version
----

should return:

[source,plaintext]
----
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
----

[arabic, start=2]
. Add the Apache repository of Cassandra to the file
`cassandra.sources.list`. The latest major version is 4.0 and the
corresponding distribution name is `40x` (with an "x" as the suffix).
For older releases use `311x` for C* 3.11 series, `30x` for 3.0, `22x`
for 2.2 and `21x` for 2.1. For example, to add the repository for
version 4.0 (`40x`):

[source,shell]
----
$ echo "deb http://www.apache.org/dist/cassandra/debian 40x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
deb http://www.apache.org/dist/cassandra/debian 40x main
----

[arabic, start=3]
. Add the Apache Cassandra repository keys to the list of trusted keys
on the server:

[source,shell]
----
$ curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
----
[source,plaintext]
----
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  266k  100  266k    0     0   320k      0 --:--:-- --:--:-- --:--:--  320k
OK
----

[arabic, start=4]
. Update the package index from sources:

[source,shell]
----
$ sudo apt-get update
----

[arabic, start=5]
. Install Cassandra with APT:

[source,shell]
----
$ sudo apt-get install cassandra
----

NOTE: A new Linux user `cassandra` will get created as part of the
installation. The Cassandra service will also be run as this user.

[arabic, start=6]
. The Cassandra service gets started automatically after installation.
Monitor the progress of the startup with:

[source,shell]
----
$ tail -f /var/log/cassandra/system.log
----

Cassandra is ready when you see an entry like this in the `system.log`:

[source,plaintext]
----
INFO  [main] 2019-12-17 03:03:37,526 Server.java:156 - Starting listening for CQL clients on localhost/127.0.0.1:9042 (unencrypted)...
----

NOTE: For information on how to configure your installation, see
http://cassandra.apache.org/doc/latest/getting_started/configuring.html[Configuring
Cassandra].

[arabic, start=7]
. Check the status of Cassandra:

[source,shell]
----
$ nodetool status
----

The status column in the output should report `UN` which stands for
"Up/Normal".

Alternatively, connect to the database with:

[source,shell]
----
$ cqlsh
----

== Installing the RPM packages

[arabic]
. Verify the version of Java installed. For example:

[source,shell]
----
$ java -version
----
[source,plaintext]
----
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
----

[arabic, start=2]
. Add the Apache repository of Cassandra to the file
`/etc/yum.repos.d/cassandra.repo` (as the `root` user). The latest major
version is 4.0 and the corresponding distribution name is `40x` (with an
"x" as the suffix). For older releases use `311x` for C* 3.11 series,
`30x` for 3.0, `22x` for 2.2 and `21x` for 2.1. For example, to add the
repository for version 4.0 (`40x`):

[source,plaintext]
----
[cassandra]
name=Apache Cassandra
baseurl=https://downloads.apache.org/cassandra/redhat/40x/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://downloads.apache.org/cassandra/KEYS
----

[arabic, start=3]
. Update the package index from sources:

[source,shell]
----
$ sudo yum update
----

[arabic, start=4]
. Install Cassandra with YUM:

[source,shell]
----
$ sudo yum install cassandra
----

NOTE: A new Linux user `cassandra` will get created as part of the
installation. The Cassandra service will also be run as this user.

[arabic, start=5]
. Start the Cassandra service:

[source,shell]
----
$ sudo service cassandra start
----

[arabic, start=6]
. Monitor the progress of the startup with:

[source,shell]
----
$ tail -f /var/log/cassandra/system.log
----

Cassandra is ready when you see an entry like this in the `system.log`:

[source,plaintext]
----
INFO  [main] 2019-12-17 03:03:37,526 Server.java:156 - Starting listening for CQL clients on localhost/127.0.0.1:9042 (unencrypted)...
----

NOTE: For information on how to configure your installation, see
http://cassandra.apache.org/doc/latest/getting_started/configuring.html[Configuring
Cassandra].

[arabic, start=7]
. Check the status of Cassandra:

[source,shell]
----
$ nodetool status
----

The status column in the output should report `UN` which stands for
"Up/Normal".

Alternatively, connect to the database with:

[source,shell]
----
$ cqlsh
----

== Further installation info

For help with installation issues, see the
http://cassandra.apache.org/doc/latest/troubleshooting/index.html[Troubleshooting]
section.
